### ISSUE TITLE
[frag4feature] XCMS features/MS2 events linkage

### ISSUE THREAD

**Issue by Hrodwin** [computational-metabolomics/msPurity#106]
Hi it's me again,
I'm currently looking at _frag4feature_ and there"s one point I failed to understand. When linking XCMS grouped features to MS2 events, it is clear to me that _"to determine if a MS2 spectra is to be linked to an XCMS grouped feature, the associated acquisition time of the MS/MS event has to be within the retention time window defined for the individual peaks associated for each file. The precursor m/z value also has to be within the user ppm tolerance to XCMS feature."_ according to the documentation.

However, there are several examples in my _frag4feature_ results for which a XCMS group is linked to a MS2 event hat has a RT not included in the XCMS group RT boundaries. Here is an example where for the same sample a XCMS group has been linked to 2 distinct XCMS groups, one of which does not include the MS2 scan in its RT bounds:

<html xmlns:v="urn:schemas-microsoft-com:vml"
xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:x="urn:schemas-microsoft-com:office:excel"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=Excel.Sheet>
<meta name=Generator content="Microsoft Excel 15">
<link id=Main-File rel=Main-File
href="file:///C:/Users/quruin/AppData/Local/Temp/msohtmlclip1/01/clip.htm">
<link rel=File-List
href="file:///C:/Users/quruin/AppData/Local/Temp/msohtmlclip1/01/clip_filelist.xml">

</head>

<body link="#0563C1" vlink="#954F72">

grpid | mz | mzmin | mzmax | rt | rtmin | rtmax | into | intb | maxo | sn | sample | filename | cid | rtminCorrected | rtmaxCorrected | inPurity | pid | precurMtchID | precurMtchScan | precurMtchRT | precurMtchMZ | precurMtchPPM | retentionTime | fileid | seqNum
-- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | -- | --
335 | 86.0964094 | 86.0963976 | 86.0964205 | 126.070401 | 119.371 | 134.774 | 3767424.9 | 3751036.11 | 293624 | 305 | 32 | Pool_TestConst_DDA40ev_POS_BD1_1_7614.mzML | 161100 | 118.220862 | 133.797612 | 0.57990155 | 7517 | 335 | 332 | 134.774 | 86.0964407 | 0.36348129 | 136.172 | 32 | 335
334 | 86.0964297 | 86.0963905 | 86.096447 | 142.249247 | 134.774 | 152.44 | 6158137.94 | 6139341.32 | 534768 | 556 | 32 | Pool_TestConst_DDA40ev_POS_BD1_1_7614.mzML | 161099 | 133.797612 | 151.370091 | 0.57990155 | 7517 | 335 | 332 | 134.774 | 86.0964407 | 0.12809378 | 136.172 | 32 | 335
374 | 88.004314 | 88.0042004 | 88.0044198 | 850.154853 | 840.493 | 904.258 | 14312595 | 14220515.8 | 263376 | 274 | 36 | Pool_TestConst_DIA30ev_POS_BD1_1_7621.mzML | 166130 | 839.274959 | 902.336281 | 0.42121007 | 14695 | 1374 | 1371 | 888.303 | 88.0044093 | 1.08290859 | 889.982 | 36 | 1374
371 | 88.0043422 | 88.0042467 | 88.0044093 | 889.218019 | 888.303 | 891.009 | 1105346.88 | 1097832.32 | 219758 | 228 | 36 | Pool_TestConst_DIA30ev_POS_BD1_1_7621.mzML | 166134 | 886.540331 | 889.218019 | 0.42121007 | 14695 | 1374 | 1371 | 888.303 | 88.0044093 | 0.76201277 | 889.982 | 36 | 1374
520 | 96.009542 | 96.0093587 | 96.0098835 | 23.7289243 | 12.349 | 53 | 1989038.65 | 1968521.44 | 81230 | 94 | 30 | Pool_TestConst_DDA20ev_POS_BD1_1_7612.mzML | 159121 | 12.3520663 | 52.4308981 | 0.55417232 | 3630 | 55 | 42 | 29.004 | 96.0097242 | 1.89833824 | 30.811 | 30 | 55

</body>

</html>

![image](https://github.com/user-attachments/assets/d9451211-02c8-43ac-893d-f194f077fe33)

Is this due to a bug or have I failed to correctly understand the operating of tje function (which is quite like to happen)?

Thanks 😊

**Comment by Hrodwin** [comment]
Just a little ping @Tomnl 😋

**Comment by Tomnl** [comment]
Sorry - I missed this. Thanks for the ping. 

If I understand the question correctly. I think this is due to the retention time match being based on the precursor scan time rather than the time of the fragmentation scan. Which I think makes some sense.

So in the above examples the precurMtchRT value is within the original non corrected rtmin and rtmax range of the XCMS peak

**Comment by Tomnl** [comment]
I guess this could be an issue if you have a long time between MS/MS scans and MS1 scans. 

Could provide an option so that it matches on MS/MS scan time rather than the precursor scan time. Would that be of interest?

**Comment by Tomnl** [comment]
If there isn't a recorded precursor scan. The retention time of the MS/MS scan is used. See here https://github.com/computational-metabolomics/msPurity/blob/master/R/purityA-frag4feature.R#L343-L346

Could add a parameter in the function so that the retentionTime of the MS/MS scan is used regardless

**Comment by Hrodwin** [comment]
Alright! I now have all the information I was looking for! No need for the addition of a new parameter don't worry, was just a misunderstanding on my part that needed further explanations. 
Thanks a lot @Tomnl

**Comment by Tomnl** [comment]
OK great. 

I will close the issue for now - but if there is any interests I can add a parameter for the above (as I think it could be useful)
