### ISSUE TITLE
purity score calculation

### ISSUE THREAD

**Issue by jsaintvanne** [computational-metabolomics/msPurity#50]
Hi Thomas,

I'm working on a file from our laboratory and we ask ourselves some questions about purity score calculation : what is the isolation window and where we can find it ?

After some searches, we find the `get_isolation_offsets` function. 

Our problem is that we can't find lines you are searching for : 
```
if (!lowFound){
      low <- as.numeric(stringr::str_match(oneLine, '^.*name=\"isolation window lower offset\" value=\"([0-9]+\\.[0-9]+).*$')[,2])
      if(!is.na(low)){lowFound=TRUE}
    }

    if (!highFound){
      high <- as.numeric(stringr::str_match(oneLine, '^.*name=\"isolation window upper offset\" value=\"([0-9]+\\.[0-9]+).*$')[,2])
      if(!is.na(high)){highFound=TRUE}
    }
```

We worked on a Thermo Q-exactive spectrometer and the line we should search is the following : 
`<precursorMz precursorScanNum="367" precursorIntensity="4.065790625e05" activationMethod="HCD" windowWideness="2.0">251.104995727539</precursorMz>`

And I add that we have a window here that we should divide by 2...

What do you think about that ? Is it something that you have already faced ?

Thanks !!

Julien

**Comment by jsaintvanne** [comment]
I found from where is the problem !
It is the format of the file... I thought there was not so much differences between `mzML` and `mzxML` but there is one : this one just before...

So what do you think about that ? Limited at `mzML` files only? Or modify a little research for windows offsets to be able to run on `mzxML` files also ?

Thanks !!

Julien

**Comment by Tomnl** [comment]
Hi @jsaintvanne,

Yes - the automatic detection of offsets is only available for mzML files - I think mzXML files are somewhat redundant now as mzML was intended to supersede the format (http://www.psidev.info/mzML). So I am not in a rush to support the format - however if it is really required we could update the parsing to support mzXML as well.

A user can add the isolation offsets themselves though using the "offsets" parameter. e.g. if the isolation window is 2 Da (i.e. 1 Da either side), offset = c(1, 1). 

Hope that answers the question

**Comment by jsaintvanne** [comment]
Hi,

Yes thanks Thomas !! It is just a question of the most practical format for scientific community :)
I just have to limit input data in wrapper to mzML files it is not a problem !

Thanks for the answer !

**Comment by Tomnl** [comment]
Hi @jsaintvanne, I have added a separate "enhancement" issue for dealing with non-mzML files, see #51.

As it could be useful to be able to do precursor ion purity calculations for mzXML files from historic datasets where it might be difficult to reconvert the raw files into mzML. 

Is it OK to close this issue now?

**Comment by jsaintvanne** [comment]
yes of course !! :) 

I have all my answers ;)
