### ISSUE TITLE
createDatabase function

### ISSUE THREAD

**Issue by jsaintvanne** [computational-metabolomics/msPurity#75]
Hi,

I would like to use the createDatabase (or create_database) function with the Galaxy wrapper (see here https://github.com/computational-metabolomics/mspurity-galaxy/blob/master/tools/msPurity/createDatabase.R)

My question is : in the documentation, you say "createdatabse replaces the create_database function" but when I go on msPurity on github, I can see that it is "create_database" function which is update ?

So which one should I use ? 
Because for the moment, I obtain this error with the wrapper and createDatabase : 
Error in if (pa@filter_frag_params$allfrag) { : 
  argument is of length zero

Because I don't want to filter something...

And I can see that I haven't this script with the "create_database" function !

So what can I do with these two functions ?

Thanks!

Julien Saint-Vanne

**Comment by Tomnl** [comment]
Hi Julien,

You should use the createDatabase function.

Regarding the error: 

Unfortunately you need to run the `filterFragSpectra` function prior to using createDatabase (if you don't want to filter anything just set all the filters to 0 and set `rmp` to `False`)

Should be a quick fix to update solve this - but I haven't got round to it yet

**Comment by jsaintvanne** [comment]
Thanks Thomas !

So I will use the good function !! :)

Just now I'm fighting with this error :
"Error in `[.data.frame`(df, , columnorder) : undefined columns selected
Calls: <Anonymous> ... custom_dbWriteTable -> update_cn_order -> [ -> [.data.frame"

Just in case you already know something about it

**Comment by Tomnl** [comment]
Could you send me the lines of code you used?

**Comment by jsaintvanne** [comment]
Ho I just use it on Galaxy instance !

So I made the peakpicking with xcms, grouping, fillpeaks, made also the purityA, f4f and now trying to create the database

Directly on W4M Galaxy. I thought that works good but actually I can't run it correctly so maybe I will switch to an R interface but it could be a Galaxy error that I made

**Comment by Tomnl** [comment]
Could you see if it works if you run filterFragSpectra after f4f?

**Comment by jsaintvanne** [comment]
> Could you see if it works if you run filterFragSpectra after f4f?

Just got the error below when I run createDatabase on Galaxy after processed filterFragSpectra also

**Comment by Tomnl** [comment]
Are you using https://workflow4metabolomics.usegalaxy.fr/

Could you share the history with me? (t.n.lawson@bham.ac.uk - user tomnl)

**Comment by jsaintvanne** [comment]
Yes exactly ! Done ! Thanks Thomas for your help :)

**Comment by Tomnl** [comment]
Thanks. 

I imported this history and ran the steps myself but I get a memory error for the createDatabase tool (see below). Do you know what memory settings were used?

```This job was terminated because it used more memory than it was allocated.
Please click the bug icon to report this problem if you need help.

**Comment by jsaintvanne** [comment]
Ho yes I have maybe done something bad... So Yann also have the memory error and I would reproduced it ! 

I find it very strange to have memory error with only 4 files during this step of the workflow which is "createDatabase" isn't it ?

**Comment by Tomnl** [comment]
Depends on how much memory was given. The SQLite table creation for can take up quite a lot of memory

**Comment by yguitton** [comment]
Hi,
The memory settings of workflow4metabolomics.usegalaxy.fr have been changed and now 8 Go can be used by SQLite table.
The tool is now ok even for huge files.
Yann

**Comment by Tomnl** [comment]
OK great. I have made an additional check for the `allfrag` error as well in the latest branch as well #72 

I will close this issue now.
