### ISSUE TITLE
msPurity spectralMatching empty for negative mode

### ISSUE THREAD

**Issue by yguitton** [computational-metabolomics/msPurity#76]
Hi Tom,

I have an issue with my negative mode metabolomics MSMS data processing with msPurity (same issue under Galaxy or under Rstudio). 
 I guess that it might be my bad, but i don't see where I'm wrong. My Galaxy history is here https://workflow4metabolomics.usegalaxy.fr/u/yguitton44/h/copy-of-metabo-neg-dda 
If you have an idea ? 

I managed to work with Positive mode but for an unknown reason I have a "No Match found" when I use the negative mode input.

I have tested manually and the MSMS of grpid 400  match Phenylalanine, on Mona web site with the accession PR309414.

Spectra extracted from MSP file generated by msPurity

NAME: MZ:164.0717 | RT:127.4 | grpid:400 | file:3 | adduct:NA
PRECURSORMZ: 164.071671352252
RETENTIONTIME: 127.374984741211
XCMS groupid (grpid): 400
COMMENT: Exported from msPurity purityA object using function createMSP, using method 'av_intra' msPurity version:1.12.2 
Num Peaks: 7
72.0085405865847	402802.96875	36.04
91.0548060473143	47103.625	4.21
103.054815151088	68894.373046875	6.16
118.066677625233	6107.96728515625	0.55
147.044825781743	1117757.375	100
163.839736077141	44750.62890625	4
164.072411612146	1085359.75	97.1

I have also check that my MetaboNEG.sqlite files from createDatabase is not empty and I found that at some point the spectralMatching function is removing all MSMS spectra from the query (the q_speakmeta is empty for negative mode MSMS)

q_speakmeta <- msPurity:::filterSMeta(purity = q_purity, pol = q_pol, 
                               instrumentTypes = q_instrumentTypes, instruments = q_instruments, 
                               sources = q_sources, pids = q_pids, rtrange = q_rtrange, 
                               con = q_con, xcmsGroups = q_xcmsGroups, spectraTypes = q_spectraTypes, 
                               accessions = q_accessions)

Many thanks for your help
Yann

**Comment by Tomnl** [comment]
Hi Yann, 

Not sure what is going on here exactly

Do you need to use "intra" averaging specifically? I ran through and got a hit for L-(-)-Phenylalanine when I averaged with all spectra ignoring intra and inter relationships (i.e. using the settings below on the averaging step)

![image](https://user-images.githubusercontent.com/5541632/89289725-a3609e00-d64f-11ea-99b7-77c4bf03198d.png)

(I typically use the intra and inter averaging separately if I have both internal (within file) and across file replication of fragmentation spectra and what to treat the averaging differently.)

Also, use the option "negative" in the library spectra settings in spectral matching, see below:

![image](https://user-images.githubusercontent.com/5541632/89290051-28e44e00-d650-11ea-898c-fdbae275a411.png)

I will look into why the "intra" averaging was giving no hits

**Comment by yguitton** [comment]
Thanks I will try that right now

msPurity is a really good tool 
Have a nice day
Yann

**Comment by Tomnl** [comment]
No worries! Thanks for using the tool! And let me know how you get on.

Here is my history with the annotation results if you wanted to check what I did for the spectral matching tool

https://workflow4metabolomics.usegalaxy.fr/u/tomnl/h/imported-copy-of-metabo-neg-dda
