### ISSUE TITLE
Correction for the align function in the spectralMatching.R

### ISSUE THREAD

**Issue by xiaodfeng** [computational-metabolomics/msPurity#79]
1. The default setting of the align function is `l_ppmProd=100, q_ppmProd=100, raDiffThres=10.` However, the default setting of l_ppmProd and q_ppmProd in the function _spectralMatching_  is 10. I believe this is a typo. My correction for the default setting is `l_ppmProd=10, q_ppmProd=10, raDiffThres=100.`

2. `intenc <- iD[ppmD==1 & iD<raDiffThres & !is.na(ppmD) & !is.na(raDiffThres)]`. In this code, ppmD stands for ppm difference, we should use ppmB, which stands for ppm bool. So my correction is `intenc <- iD[ppmB==1 & iD<raDiffThres & !is.na(ppmD) & !is.na(raDiffThres)]`

**Comment by Tomnl** [comment]
Thanks for spotting this @xiaodfeng, very useful!

 I have made the changes in github and pushed to both dev and stable of bioconductor. 

If it is OK with you, I will close this issue now

**Comment by xiaodfeng** [comment]
Thank you for maintaining this package. It is very useful for identification in lipidomics. Feel free to close it.
