### ISSUE TITLE
Processing Agilent QToF files

### ISSUE THREAD

**Issue by yguitton** [computational-metabolomics/msPurity#88]
Hi @Tomnl,

I'm running some Agilent QToF files and I'm facing a new issue in R.

` purityA(file,offset=c(0.65,0.65), mostIntense = TRUE, nearest = FALSE, ppmInterp = 7)`
MS2 data has no associated scan data, will use most recent full scan for information
Error in assessPuritySingle(filepth = pa@fileList[[i]], mostIntense = mostIntense,  : 
  task 1 failed - "non-numeric argument to mathematical function"

the file is here https://workflow4metabolomics.usegalaxy.fr/datasets/086de8e126a393ff/display?to_ext=mzml

Any clue for me?
Many Thanks
Yann

**Comment by Tomnl** [comment]
Hi @yguitton ,

I think you need to just change 'offset' to 'offsets'. Hopefully that will fix it.

Were you running in R or Galaxy?

Tom

**Comment by yguitton** [comment]
Hi @Tomnl 

The problem seems to be the mzML file itself. I have tried with other Agilent QToF files and purityA is ok.
 For the initial file the error message is 
Error in assessPuritySingle(filepth = pa@fileList[[i]], mostIntense = mostIntense,  : 
  task 1 failed - "argument is of length zero"

I will investigate assessPuritySingle function but I think the problem come from the MSMS method used 

Best 
Regards

**Comment by Tomnl** [comment]
I hope this issues was resolved. If not, I can re open and I can investigate further
