### ISSUE TITLE
Installing the msPurity package in R studio

### ISSUE THREAD

**Issue by Haassress** [computational-metabolomics/msPurity#95]
Greetings,
I was trying to install the msPurity package. But I am getting two error messages
1) packages ‘BiocVersion’, ‘msPurity’ are not available for Bioconductor version '3.15'
2) 'SSL peer certificate or SSH remote key was not OK' or 'Problem with the SSL CA cert (path? access rights?)'

Can you please help? Is there any other way I can install the package?

**Comment by Tomnl** [comment]
Hi,

Did you install with these commands?

```
if (!requireNamespace("BiocManager", quietly = TRUE))
    install.packages("BiocManager")
BiocManager::install("msPurity")

```

**Comment by Haassress** [comment]
I am using Windows.
I need to read the mzML file into R for msPurity.
I have converted my .raw files to mzML using MSconvert.
I have installed the msPurityData package to do the example you described and it worked perfectly (See below).
But I am failing to import my own mzML files in to R.
To be honest with you, I am not an R expert. I am a learner. I really need the msPurity information for my data.
I would appreciate if you can send me an R code to import the data. I tried several times with different ways.
IT keeps telling me there is  no file list

My mzML is in: C/Haile/TEST.mzML


***@***.***

Example, does something like these(below) make sense?. I couldn’t figure out where I am doing it wrong. Please help.

***@***.***
***@***.***

**Comment by Haassress** [comment]
Hi Thomas,
I just want to update you. I have been trying the importing issue. I tried few more methods and I am getting the following error.
Could you help from here? Is this the issue of the directory or the file conversion? I used MSconvertGUI(64) to convert the files and I used pick peaking as a filter, which I believe is fixing the issue of centroid data. Kindly assist.

***@***.***

Best Regards,
Haile

**Comment by Tomnl** [comment]
@Haassress I will close this issue now as we have resolved this issue via email correspondence. 

Noting that msPurity installs and works fine on Windows R v4.2 when tested on other computers.

And noting that one of the problems of reading in the files was due to using a recent version of msconvert to create the mzML files and reading them in with an older version of R and msPurity.

**Comment by Haassress** [comment]
Thank you for all the supports
________________________________
