### ISSUE TITLE
unused argument (xcmsObj = xcmsObj)

### ISSUE THREAD

**Issue by cyan20200410** [computational-metabolomics/msPurity#96]
Hi experts

I am following the package here: http://bioconductor.org/packages/release/bioc/vignettes/msPurity/inst/doc/msPurity-lcmsms-data-processing-and-spectral-matching-vignette.html

I have the following error: 
===
Error in frag4feature(pa = pa, xcmsObj = xcmsObj) : 
unused argument (xcmsObj = xcmsObj)
===
while trying use the following script:
pa <- frag4feature(pa = pa, xcmsObj = xcmsObj)
===

Could anyone help please?

Cyan

**Comment by Tomnl** [comment]
Hi Cyan,

I think you might be using an older version of msPurity. Could you provide some more information please (see below)

What R version and msPurity version are you using?
(Copy the output from the `sessioninfo()` command)

Can you copy a snippet of the code that you used?


(if you need to use the older version of msPurity use the following command `frag4feature(pa = pa, xset = xcmsObj)` )

Tom
